Updates for second UE.

diff --git a/bin/handover b/bin/handover
--- a/bin/handover
+++ b/bin/handover
@@ -1,6 +1,7 @@
 #/bin/bash
 UPDATE_ATTENS_SCRIPT=/local/repository/bin/update-attens
-DST_RU=$1
+UE=$1
+DST_RU=$2
 ATTEN_STEP=5
 START_ATTEN_SRC=0
 START_ATTEN_DST=60
@@ -10,30 +11,42 @@ usage() {
 usage:
     handover -h
         show this help message
-    handover <dst_ru>
-        handover UE to <dst_ru> using 5 dB atten steps for <dwell_time> seconds
-        <dst_ru> can be bru1 or bru2 (assumes UE is currently attached via the other RU)
+    handover <ue> <dst_ru>
+        handover <ue> to <dst_ru> using 5 dB atten steps for <dwell_time> seconds
+        <dst_ru> can be ru1 or ru2 (assumes <ue> is currently attached via the other RU)
+        <ue> can be ue1 or ue2
 EOF
 }
 
-if [ -z $DST_RU ]; then
+# if length of arguments is less than 2, show usage and exit
+if [ $# -lt 2 ]; then
   usage; exit 1
+fi
+
+if [ $UE != "ue1" ] && [ $UE != "ue2" ]; then
+  echo "invalid ue"; usage; exit 1
 fi
 
 if [ $DST_RU != "ru1" ] && [ $DST_RU != "ru2" ]; then
   echo "invalid dst_ru"; usage; exit 1
 fi
 
-if [ $DST_RU == "ru1" ]; then
-  DST_RU_GROUP="ru1ue"
-  SRC_RU_GROUP="ru2ue"
-else
-  DST_RU_GROUP="ru2ue"
-  SRC_RU_GROUP="ru1ue"
+if [ $DST_RU == "ru1" ] && [ $UE == "ue1" ]; then
+  DST_RU_GROUP="ru1ue1"
+  SRC_RU_GROUP="ru2ue1"
+elif [ $DST_RU == "ru1" ] && [ $UE == "ue2" ]; then
+  DST_RU_GROUP="ru1ue2"
+  SRC_RU_GROUP="ru2ue2"
+elif [ $DST_RU == "ru2" ] && [ $UE == "ue1" ]; then
+  DST_RU_GROUP="ru2ue1"
+  SRC_RU_GROUP="ru1ue1"
+elif [ $DST_RU == "ru2" ] && [ $UE == "ue2" ]; then
+  DST_RU_GROUP="ru2ue2"
+  SRC_RU_GROUP="ru1ue2"
 fi
 
 handover() {
-  echo "handing over UE to $TARGET_RU..."
+  echo "handing over $UE to $TARGET_RU..."
   for atten in $(seq $START_ATTEN_SRC $ATTEN_STEP $START_ATTEN_DST); do
     $UPDATE_ATTENS_SCRIPT $SRC_RU_GROUP $((START_ATTEN_SRC + atten))
     $UPDATE_ATTENS_SCRIPT $DST_RU_GROUP $((START_ATTEN_DST - atten))
